name: Kscan build

on:
#   push:
  workflow_dispatch:

jobs:

  linuxbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.10
    - name: linux Build
      run: |
        go mod tidy
        go build kscan.go -o kscan_amd64 -v
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: # optional, default is artifact
          kscan_amd64
        # A file, directory or wildcard pattern that describes what to upload
        path: 
          ./kscan_amd64
        # The desired behavior if no files are found using the provided path.

  macbuild:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.10
    - name: mac Build
      run: |
        go mod tidy
        go build kscan.go -o kscan_darwin -v
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: # optional, default is artifact
          kscan_darwin
        # A file, directory or wildcard pattern that describes what to upload
        path: 
          ./kscan_darwin
        # The desired behavior if no files are found using the provided path.

  winbuild:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.10
    - name: Windows Build
      run: |
        go mod tidy
        go build kscan.go -o kscan64.exe -v
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: # optional, default is artifact
          kscan64.exe
        # A file, directory or wildcard pattern that describes what to upload
        path: 
          ./kscan64.exe
        # The desired behavior if no files are found using the provided path.
